{"name": "Логин юзера с некорректным паролем или логином", "status": "passed", "description": "Проверяем, что при логине с некорректным паролем или логином возвращается ошибка", "steps": [{"name": "Извлекаем данные для авторизации юзера", "status": "passed", "parameters": [{"name": "credentials", "value": "{'email': 'karl_17+70043221@example.org', 'password': 'looaxfouae', 'name': 'yszvzrmhvk'}"}], "start": 1723315048779, "stop": 1723315048779}], "parameters": [{"name": "login_type", "value": "'email'"}], "start": 1723315048515, "stop": 1723315048990, "uuid": "426bb65b-bcf1-4b52-8264-ecc267992233", "historyId": "a62ee465835fae24575352aaf0ec3224", "testCaseId": "07f5661e1ab0cebc2b1da901e6822b05", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "MacBook-Pro-4.local"}, {"name": "thread", "value": "11097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}